name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # change if your branch is "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # If you’re using Tailwind CLI to build CSS
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build CSS with Tailwind
        run: npx @tailwindcss/cli -i ./input.css -o ./output.css

      # Deploy static files to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .   # root folder (where index.html is)
